### ISSUE TITLE
Preserve theme for sharing

### ISSUE THREAD

**Issue by rew1nter** [topi314/gobin#29]
Hey it'd be very nice if the theme I set was saved with the paste when another person sees the code

**Comment by topi314** [comment]
You can already append a `style=style_value`  query param to the URL.
You can find a full list of style values [here](https://github.com/topi314/gobin/tree/v2/styles) and [here](https://github.com/topi314/chroma/tree/master/styles/embedded)

As for sharing I think the preference of the user should always come first, that means even if you set the `style` query param and a user selected a specific theme that will be applied.

I wouldn't want to get blasted with whitemode just because someone put it in the URL :)
